// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6FTgDWZcIsUWoUb2kMEpQ-Ta-tuVFQUc',
    appId: '1:534632828391:web:59db8d7809bcac20eb0142',
    messagingSenderId: '534632828391',
    projectId: 'fashion-store-99c27',
    authDomain: 'fashion-store-99c27.firebaseapp.com',
    storageBucket: 'fashion-store-99c27.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD14wFk16knC1MukzAs_YB68rTMf2buO4',
    appId: '1:534632828391:android:0abe450da9941e14eb0142',
    messagingSenderId: '534632828391',
    projectId: 'fashion-store-99c27',
    storageBucket: 'fashion-store-99c27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGtIOzTGL0A-nZsckmgqr1lwbtPfYJxqU',
    appId: '1:534632828391:ios:0cdfbdea938cf9e1eb0142',
    messagingSenderId: '534632828391',
    projectId: 'fashion-store-99c27',
    storageBucket: 'fashion-store-99c27.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGtIOzTGL0A-nZsckmgqr1lwbtPfYJxqU',
    appId: '1:534632828391:ios:ff079c4f2920fd5beb0142',
    messagingSenderId: '534632828391',
    projectId: 'fashion-store-99c27',
    storageBucket: 'fashion-store-99c27.appspot.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
